from database import SessionLocal, engine, Base
from models import Product

Base.metadata.create_all(bind=engine)

db = SessionLocal()

products = [
    Product(
        title="Жіноча чорна сукня",
        description="Елегантна чорна жіноча сукня для вечірніх подій.",
        brand="Zara",
        category="dress",
        style="elegant",
        color="black",
        gender="female",
        size="M",
        material="cotton",
        price=2199,
        store="Zara",
        image_url="/static/images/black_elegant_dress.jpg",
        product_url="https://www.zara.com/ua/uk/%D1%81%D1%83%D0%BA%D0%BD%D1%8F-%D0%BC%D1%96%D0%B4%D1%96-%D0%B7-%D0%BF%D0%BE%D0%BB%D1%96%D0%B0%D0%BC%D1%96%D0%B4%D0%BE%D0%BC-p01355031.html?v1=529543986&v2=2420904"
    ),
    Product(
        title="Жіноча червона сукня",
        description="Елегантна червона сукня для святкових подій та вечірнього образу.",
        brand="Mango",
        category="dress",
        style="elegant",
        color="red",
        gender="female",
        size="S",
        material="viscose",
        price=450,
        store="Shafa",
        image_url="/static/images/red_elegant_dress.jpg",
        product_url="https://shafa.ua/uk/women/platya/maksi/208771585-plate-zhenskoe-hlopok-mango-pl46-48"
    ),
    Product(
        title="Жіноча бежева сукня",
        description="Легка бежева сукня у повсякденному стилі для прогулянок і зустрічей.",
        brand="Reserved",
        category="dress",
        style="casual",
        color="beige",
        gender="female",
        size="M",
        material="linen",
        price=399,
        store="Reserved",
        image_url="/static/images/beige_elegant_dress.jpg",
        product_url="https://www.reserved.com/ua/uk/suknia-zhinocha-1958t-08x?srsltid=AfmBOopzslANwkbnpDjPtEBQGI9NiD322ie2Q2w1wK9z0L6tE7irKbn_"
    ),
    Product(
        title="Чоловіче чорне худі",
        description="Спортивне чорне худі для повсякденного носіння у прохолодну погоду.",
        brand="Nike",
        category="hoodie",
        style="sport",
        color="black",
        gender="male",
        size="L",
        material="polyester",
        price=4390,
        store="Intertop",
        image_url="/static/images/black_hoodie_man.jpg",
        product_url="https://intertop.ua/uk-ua/product/sweaters-and-sweaters-nike-10325206/"
    ),
    Product(
        title="Жіноче біле худі",
        description="Зручне біле худі oversize для casual образів і щоденного використання.",
        brand="H&M",
        category="hoodie",
        style="casual",
        color="white",
        gender="female",
        size="M",
        material="cotton",
        price=400,
        store="Shafa",
        image_url="/static/images/white_hoodie_woman.jpg",
        product_url="https://shafa.ua/uk/women/kofty/hudi/163761449-belyy-hudi-hm"
    ),
    Product(
        title="Унісекс сіре худі",
        description="Сіре унісекс худі для прогулянок, навчання та комфортного щоденного носіння.",
        brand="Pull&Bear",
        category="hoodie",
        style="casual",
        color="gray",
        gender="unisex",
        size="L",
        material="cotton",
        price=1499,
        store="Pull&Bear",
        image_url="/static/images/unisex_hoodie_gray.jpg",
        product_url="https://www.pullandbear.com/ua/%D1%85%D1%83%D0%B4%D1%96-crew-studios-%D0%B7-%D0%BA%D0%B0%D0%BF%D1%8E%D1%88%D0%BE%D0%BD%D0%BE%D0%BC-l03550322?cS=811&pelement=721446145"
    ),
    Product(
        title="Чоловіча чорна футболка",
        description="Базова чорна футболка у спортивному стилі для щоденного використання.",
        brand="Adidas",
        category="tshirt",
        style="sport",
        color="black",
        gender="male",
        size="M",
        material="cotton",
        price=2299,
        store="Adidas",
        image_url="/static/images/black_shirt_man.jpg",
        product_url="https://www.adidas.ua/futbolka-adidas-z-n-e-sportswear-je3069-1"
    ),
    Product(
        title="Жіноча біла футболка",
        description="Базова біла футболка для повсякденних образів та поєднання з джинсами.",
        brand="Uniqlo",
        category="tshirt",
        style="casual",
        color="white",
        gender="female",
        size="S",
        material="cotton",
        price=1407,
        store="Rozetka",
        image_url="/static/images/white_shirt_woman.jpg",
        product_url="https://rozetka.com.ua/ua/uniqlo-1159847560/p559294161/"
    ),
    Product(
        title="Унісекс синя футболка",
        description="Синя футболка у повсякденному стилі для навчання, прогулянок і відпочинку.",
        brand="Cropp",
        category="tshirt",
        style="casual",
        color="blue",
        gender="unisex",
        size="M",
        material="cotton",
        price=599,
        store="Cropp",
        image_url="/static/images/blue_shirt_unisex.jpg",
        product_url="https://www.cropp.com/ua/uk/chorna-futbolka-z-pryntom-682hy-59x"
    ),
    Product(
        title="Жіночі бежеві штани",
        description="Класичні бежеві штани з льону для офісного та повсякденного стилю.",
        brand="Mango",
        category="pants",
        style="classic",
        color="beige",
        gender="female",
        size="M",
        material="linen",
        price=2599,
        store="Intertop",
        image_url="/static/images/beige_pants_woman.jpg",
        product_url="https://intertop.ua/uk-ua/product/pants-mango-11260068/"
    ),
    Product(
        title="Чоловічі чорні штани",
        description="Класичні чорні чоловічі штани для офісу, навчання та ділових зустрічей.",
        brand="Reserved",
        category="pants",
        style="classic",
        color="black",
        gender="male",
        size="L",
        material="cotton",
        price=1299,
        store="Reserved",
        image_url="/static/images/black_pants_man.jpg",
        product_url="https://www.reserved.com/ua/uk/kartati-shtany-chynosy-yv905-99x"
    ),
    Product(
        title="Жіночі сині джинси",
        description="Сині джинси прямого крою для щоденного casual образу.",
        brand="Levis",
        category="jeans",
        style="casual",
        color="blue",
        gender="female",
        size="M",
        material="denim",
        price=2090,
        store="Rozetka",
        image_url="/static/images/blue_jeans_woman.jpg",
        product_url="https://rozetka.com.ua/ua/591231790/p591231790/"
    ),
    Product(
        title="Чоловічі сині джинси",
        description="Зручні чоловічі сині джинси для повсякденного носіння.",
        brand="Levis",
        category="jeans",
        style="casual",
        color="blue",
        gender="male",
        size="L",
        material="denim",
        price=3276,
        store="Rozetka",
        image_url="/static/images/blue_jeans_man.jpg",
        product_url="https://rozetka.com.ua/ua/levis-1159858867/p591066994/"
    ),
    Product(
        title="Жіноча сіра куртка",
        description="Сіра куртка для прохолодної погоди, прогулянок та осіннього сезону.",
        brand="Columbia",
        category="jacket",
        style="casual",
        color="gray",
        gender="female",
        size="M",
        material="polyester",
        price=3499,
        store="Columbia",
        image_url="http://127.0.0.1:8000/static/images/jacket_gray.jpg",
        product_url="https://example.com/jacket-gray"
    ),
    Product(
        title="Чоловіча чорна куртка",
        description="Тепла чорна куртка для осені та прохолодної погоди.",
        brand="The North Face",
        category="jacket",
        style="sport",
        color="black",
        gender="male",
        size="L",
        material="polyester",
        price=4299,
        store="The North Face",
        image_url="http://127.0.0.1:8000/static/images/jacket_black.jpg",
        product_url="https://example.com/jacket-black"
    ),
    Product(
        title="Жіноче бежеве пальто",
        description="Елегантне бежеве пальто для осіннього образу та ділового стилю.",
        brand="Reserved",
        category="coat",
        style="classic",
        color="beige",
        gender="female", 
        material="wool",
        price=4599,
        store="Reserved",
        image_url="http://127.0.0.1:8000/static/images/coat_beige.jpg",
        product_url="https://example.com/coat-beige"
    ),
    Product(
        title="Чоловіче чорне пальто",
        description="Класичне чорне чоловіче пальто для офісу, міста та холодної погоди.",
        brand="Zara",
        category="coat",
        style="classic",
        color="black",
        gender="male",
        size="L",
        material="wool",
        price=4999,
        store="Zara",
        image_url="http://127.0.0.1:8000/static/images/coat_black.jpg",
        product_url="https://example.com/coat-black"
    ),
    Product(
        title="Жіноча зелена сорочка",
        description="Легка зелена сорочка для офісу, навчання та повсякденного образу.",
        brand="Mohito",
        category="shirt",
        style="classic",
        color="green",
        gender="female",
        size="S",
        material="viscose",
        price=1299,
        store="Mohito",
        image_url="http://127.0.0.1:8000/static/images/shirt_green.jpg",
        product_url="https://example.com/shirt-green"
    ),
    Product(
        title="Чоловіча біла сорочка",
        description="Класична біла чоловіча сорочка для ділових зустрічей та офісного стилю.",
        brand="H&M",
        category="shirt",
        style="classic",
        color="white",
        gender="male",
        size="M",
        material="cotton",
        price=1499,
        store="H&M",
        image_url="http://127.0.0.1:8000/static/images/shirt_white.jpg",
        product_url="https://example.com/shirt-white"
    ),
    Product(
        title="Унісекс чорний світшот",
        description="Чорний світшот у повсякденному стилі для комфортного щоденного носіння.",
        brand="Bershka",
        category="hoodie",
        style="casual",
        color="black",
        gender="unisex",
        size="M",
        material="cotton",
        price=1199,
        store="Bershka",
        image_url="/static/images/black_hoodie_unisex.jpg",
        product_url="https://www.bershka.com/ua/%D1%81%D0%B2%D1%96%D1%82%D1%88%D0%BE%D1%82-%D0%BE%D0%B2%D0%B5%D1%80%D1%81%D0%B0%D0%B9%D0%B7-%D0%BC%27%D1%8F%D0%BA%D0%B8%D0%B9-%D0%BD%D0%B0-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%96-%D0%BC%D0%BE%D0%B4%D0%B0%D0%BB%D1%83-c0p209126866.html?colorId=800"
    ),
]

db.query(Product).delete()
db.add_all(products)
db.commit()
db.close()

print("Seed completed.")